/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.swc_msgs
{
    public class WaypointsResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "swc_msgs/Waypoints";

        public Gps[] waypoints;

        public WaypointsResponse()
        {
            this.waypoints = new Gps[0];
        }

        public WaypointsResponse(Gps[] waypoints)
        {
            this.waypoints = waypoints;
        }
    }
}
