/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.swc_msgs
{
    public class Control : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "swc_msgs/Control";

        public float speed;
        public float turn_angle;

        public Control()
        {
            this.speed = 0.0f;
            this.turn_angle = 0.0f;
        }

        public Control(float speed, float turn_angle)
        {
            this.speed = speed;
            this.turn_angle = turn_angle;
        }
    }
}
